apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: discourse
spec:
  secretName: discourse-tls
  dnsNames:
  - "community.techwerkers.nl"
  issuerRef:
    name: acme
    kind: ClusterIssuer
