apiVersion: v1
kind: Secret
metadata:
    name: discourse-discourse
type: Opaque
stringData:
    DISCOURSE_DB_PASSWORD: ENC[AES256_GCM,data:jjid961KjIXUI382OTImRItVDDznFtDW/t66cq7SPm1fy4ztra8JrVeczF6zlKCbZT+uuXKpxa1N55CYKctgLw==,iv:gDcVOQra9Y4vkBxkDp+/sXPWTPLM3824EhD+AKCLjoE=,tag:PfLwzyty0F8F9le2blBrSA==,type:str]
    DISCOURSE_SMTP_PASSWORD: ENC[AES256_GCM,data:VhyVH4LATBbVVLcUtLYhuvE0wXnTlvBgr98pQ6MVL3c=,iv:VxQPDn2KP0v/k5C04XiEtWtOCK7T6EIfzGHAGKcAj3Y=,tag:vTIkwPK1lQiO6h/mWi86pg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIc2VDRUs0b1Rjc3I0QXVw
            ME44U3FLVXZIYnBtemZOeHJ2MGc5R1NEajNnCjdQN1hPZzhDZXp4VVFuN1VuWDlm
            Q2s4OENXeE5nbmxvYmI0YmNDTVBkRHcKLS0tIGVSZEdUTXFYb1Nsajc2SG9iNlVn
            T09CbXovbkJDVVZHeGpqOFcwSUpoOEUKo59Wq6wDcQb+LGhJ19cr7mCm6tR3sHyO
            Z9qQU44jmqvyPFEhzy9P7Ir7UZgilCHqLF7W8ld9+vp51jRJULCahw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
    lastmodified: "2026-07-18T14:00:26Z"
    mac: ENC[AES256_GCM,data:yS2OTZP56uS1xqISgoCpVusrvRmYSh55r/T9YgRqvY4W/8I54QSvbVA6LW6qPGlld2xth39986y887VTtfBz+/DC/ty1bxaBTuYTXM0KPCmvFaNVtark3mFf98U7TywLApG3xVj2v/R4KHt8Coyi+0E5tyHWXAgYeZfP0Kxban0=,iv:5oc5Ds1WZ+aWrs3Ackk1PUmeKdgkaOewMZhg3mTnw3U=,tag:Wq1XprBNdGKHa4C8jQVI0g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
