apiVersion: v1
kind: Secret
metadata:
    name: discourse-postgres
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:wlEbm09oYGlPlhuIcaTlHHKQZ2gMMt4g/VyO1rCP65pdZXaLrjFSz4UVfVielcgqtirXli1VSQz2a8o93+84rA==,iv:5Ri8fqfQONEJcKuzdl804On3SjM6s0C/Ac7qbDaZxmc=,tag:zC4rdy5XR8JwDmoRYhXCbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdHlVNHpwaURwQmtwc0pw
            L3BlSktCSElmMlQ4UDV1eGMyYnNPZS9idmlVCkxwcUZGZlRGdmtnTFNDOWtVWSt6
            TDBtWGdyelNxTVhoY04vb1pZKzlXL2cKLS0tIHpWNm0wbElLV2NDM2dLTlV3ZXg0
            clpzNXJLREdKOHd5RTFnRFdxMEZQNUEKhDAKdW8cIeHzVIMH1CSJnNkhdhxO6bO4
            lBsX++BoDd1tDSoMFXR6EpNd+JVDp6IpxEnrui6/406+x1lPpF4/xw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
    lastmodified: "2026-07-18T15:10:54Z"
    mac: ENC[AES256_GCM,data:3heZh1kjTR7slJFo4ff08rnTCaXhrKiVjHpRA4I9TWLstDbImHjNfPn1R5hmQ+bd3JCtMNi3BKkzzKl+ENvNnFimcXgL5V+cAydw5OXxlwrUPYBajTPKDeNRI79bkhNyjgtUJXfruqF8oN/LVwLgWdCHDKSZota0W87FQGrPFPs=,iv:DeVZw4z8Edz0wHE+oCWbQ5+oXA3hWEpPVIvoq2MoySc=,tag:9FhRBcjsNusqACEbtzr2sQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
