apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- https://github.com/kubernetes/kube-state-metrics//examples/standard?timeout=120&ref=v2.19.0
- servicemonitor.yaml
