apiVersion: v1
kind: Secret
metadata:
    name: n8n-env
    namespace: n8n
type: Opaque
stringData:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:5s/e9G3BMeVvfkpLTgxfkLZVPS3pkzOI4icHquKuyfQ=,iv:QKiJ9L87RE8mHYPyKns7d2wEfEww8OAEiC6uCWrJbFw=,tag:KtJVhXCQ9Z4FRVMHyA0yyg==,type:str]
    N8N_SMTP_PASS: ENC[AES256_GCM,data:DiOPejp7F/7iV/STSor68JapM670huevNV4uradu6U0=,iv:jHeOUDzNuoDtaWRqB0yxYz2TNlbLT6gViEPkS/r84Wc=,tag:zB6UqE4SIe9jGiM+HH4bUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOWFZK0F5b2tXeEJ0clB3
            R3pFY3FDb0NJVVlDenVrZ0I2QStHQmVvYzFBCnhzN1VFYWNMekVzZzB3SzRXQkhk
            Q3JZSXV1M0g3UUxsUW1kb3VOU1ZGbEUKLS0tIEJFMXZia3JYUzVWdlZPdFhBZ29P
            ako3VWNGMFlteFZ6aHRCYWlXdk00UFUKHNSOzmluH1LhHUkXSSbdh5Ud3RHEr0h/
            jaVEG5HqcDSWyuuWB4jgJ560ulkH8pub1MUlrQ3Vi3+t0M8jKFvkVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
    lastmodified: "2026-05-26T09:27:43Z"
    mac: ENC[AES256_GCM,data:BHVhAA+IIkzdZQI/v74/PKVCqe9S0xnT2ojJ6Otsku9lRRIW2BO/NK1cCpgahxhILvIZwHjcCIlpS/xjo+o6ZQTUYjPQuWlobaTh/yyLvgleaJw42XWqAcBDxewZpbacfRMfNl0B0fkxoYHbQP1cTIMHT3MKN5FXM9pQbbdaW5E=,iv:eh0TvcvL8pgnQkjkKfhMes1QTFtpEhbSicabfNkOUtg=,tag:9eLwniSle+smARcjr5AbyQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
