apiVersion: v1
kind: Secret
metadata:
    name: n8n-postgres
    namespace: n8n
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:pOzC2KwM9qcYwCfbGI/57WSMN8VkjmVwcddnDNSyf+w=,iv:QXJUYBEUcMKas6xlz+C3S4m97Df3EF0NvUEKHpSHXIg=,tag:vTzYipZ0E7LsQCqv+I5xbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYzNuRWdXSS9OdC9PaXk5
            WnEyVE5PcWVqQ01BM0dTN0tyQmU1UjloZEZnCnZEQUJCRm9FaWxMcHFaS0RjSGwy
            QWpHQVJ5Zm5zVmdkNmluTThqVGJKdzAKLS0tIHVJam5ZWkJzS1dyWUU5WjdlWjRk
            UzY4dnlBM3BCaGVheG1Rb3RSaGtWcnMKkdigj3K49E0NcUQRd58O2EiB9Qx3Ld6U
            MbmQIY5HtSn5NW1m0i8NDXZyf8LiuLOUUQ2M076siDElEdZHYZjZaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
    lastmodified: "2026-05-26T09:27:56Z"
    mac: ENC[AES256_GCM,data:qEvkwIttvAq4PGYzLgeNkZfFdQs9YHUB7iPuzBJkSkOdEelYhLa9edmE1aKVJAYbRS/qooaIAIYyLHwK3RUn6iZuKta5a+PkB4gC2qlRWrd7ibu4O+UoyHUIeY0uNSh/nDNp6JLV7DMQjuTEUp0g1ecvLcj65Igbwg24G3nTMNQ=,iv:gEi8wDuCBwjKahopO5i8NQ7uKz2QykmIyQjP1b8WhFY=,tag:0FYFEToeb1+6UmkVE6CbYQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
