apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik
  namespace: kube-system
  labels:
    prometheus: scrape
spec:
  jobLabel: traefik
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    scheme: http
    metricRelabelings:
    - targetLabel: cluster
      replacement: hetzner-01
      action: replace
    honorLabels: true
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
