apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tw-matrix

resources:
- certificate.yaml
- gateway.yaml
- httproute.yaml
- ns.yaml
- service.yaml
- statefulset.yaml
# mautrix-discord bridge
- service-mautrix-discord.yaml
- statefulset-mautrix-discord.yaml

configMapGenerator:
- name: tw-matrix-tuwunel-config
  files:
  - tuwunel.toml 

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: matrix
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
  files:
  - ./secret.enc.yaml 
