apiVersion: v1
kind: Secret
metadata:
    name: tw-matrix-tuwunel
    namespace: tw-matrix
type: Opaque
stringData:
    .reg_token: ENC[AES256_GCM,data:cq/CxQxiK6BFtXfFBFqDfXOHKIWOF1MzhBY=,iv:M53495LJ6Yc+nyG2lyJVpf0OWLW5JxZH/UPnWUtg6uc=,tag:b2m4syuIpTOrix4kSy5QwQ==,type:str]
    .turn_secret: ENC[AES256_GCM,data:p/JY1wZ3ZexVt15Hxut8PjlqFXnYbIJU4bBIDVBs1f2fIDummt0uSjoDKQE0G4OpHmFYE0Zpn6kzB2oy2gzszw==,iv:OdNTTMJgFlrSJRoFYTgrjTHh+vG9laVmnfZpP2tYwy8=,tag:ZgK6vhLYCZoX+7w7mSb84A==,type:str]
sops:
    age:
        - recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRTc4Z3JhVS9DQWtKUFBB
            TEJ4eThMbTFSNFNmRGNaWUgrY2VJOXFBL3dvCmlmSnZ6aExoYTZjUC8waTFjUHJr
            eUZBQy9hZ21QVUJ2ZmF4K2diQmMyVzAKLS0tIFBVYk9tTEpXa09GYTh2SzFnSm5u
            N3Fod3FBTkJVV1QzalBtUGwvMHRDWEEKKzpwFyV9ZcmnqKd9de9eVvuC6bAd4gVD
            d58dZqCAJtQP/XgX71bLRfLMykr+777QNuaZn2BQaSn9TB8JDxtwLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T08:13:07Z"
    mac: ENC[AES256_GCM,data:wffiWaMZre9aJLJGWrXOYogwfYSG4XMseH/ALL7h2d1Z2nDoUmTEQSOHbM3DfcxBRqesLIv9bBwtcVHbHItKE9SuiYStTXw6LBbnl1jY5pEjonzCZd2DcikZMSFc/rJi6/y7TTXzVLbGMF/yKOazMpGQG00ws+NtVALdBQJVVPE=,iv:YROfj4wDjqvSs/6kdXz3yCg5NcViufzMfkj6o8539NY=,tag:IMkq/L9m49SeDevgeOu9hQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
