apiVersion: v1
kind: ConfigMap
metadata:
  name: espocrm-daemon-env
data:
  ESPOCRM_CONFIG_DAEMON_MAX_PROCESS_NUMBER: "5"
  ESPOCRM_CONFIG_DAEMON_INTERVAL: "10"
  ESPOCRM_CONFIG_DAEMON_PROCESS_TIMEOUT: "3600"
