apiVersion: apps/v1
kind: Deployment
metadata:
  name: espocrm-espocrm
  labels:
    app: espocrm-espocrm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: espocrm-espocrm
  template:
    metadata:
      labels:
        app: espocrm-espocrm
    spec:
      containers:
      - name: espocrm
        image: espocrm/espocrm:latest # Overridden
        envFrom:
        - configMapRef:
            name: espocrm-espocrm-env
        - secretRef:
            name: espocrm-env
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 512Mi
        volumeMounts:
        - name: espocrm-www
          mountPath: /var/www/html
        - name: espocrm-customisations
          mountPath: /var/www/html/custom/Espo/Custom/Classes/Select/Lead/PrimaryFilters/RequiresReview.php
          subPath: leads-filters-RequiresReview.php
        - name: espocrm-customisations
          mountPath: /var/www/html/custom/Espo/Custom/Resources/metadata/selectDefs/Lead.json
          subPath: selectdefs-lead.json
        - name: espocrm-customisations
          mountPath: /var/www/html/custom/Espo/Custom/Resources/metadata/clientDefs/Lead.json
          subPath: clientdefs-lead.json
        - name: espocrm-customisations
          mountPath: /var/www/html/custom/Espo/Custom/Resources/i18n/en_US/Lead.json
          subPath: i18n-en_US-lead.json
      volumes:
      - name: espocrm-www
        persistentVolumeClaim:
          claimName: espocrm-www
      - name: espocrm-customisations
        configMap:
          name: espocrm-customisations
          defaultMode: 420
