apiVersion: apps/v1
kind: Deployment
metadata:
  name: espocrm-espocrm
  labels:
    app: espocrm-espocrm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: espocrm-espocrm
  template:
    metadata:
      labels:
        app: espocrm-espocrm
    spec:
      initContainers:
      - name: cp-customizations
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "[INFO] Extracting customizations.tar.gz"
          tar -xvzf /tmp/customizations.tar.gz -C /tmp/
          ls -lahR /tmp/customizations
          cat /tmp/customizations/custom/Espo/Custom/Resources/selectDefs/*.json
          echo "[INFO] Copying customizations/custom"
          cp -Rv /tmp/customizations/custom /var/www/html
          echo "[INFO] Ensuring ownership to www-data for /var/www/html/custom"
          chown -R www-data:www-data /var/www/html/custom
          echo "[INFO] Done"
        volumeMounts:
        - name: espocrm-www
          mountPath: /var/www/html
        - name: espocrm-customisations
          mountPath: /tmp/customizations.tar.gz
          subPath: customizations.tar.gz
      containers:
      - name: espocrm
        image: espocrm/espocrm:latest # Overridden
        envFrom:
        - configMapRef:
            name: espocrm-espocrm-env
        - secretRef:
            name: espocrm-env
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 512Mi
        volumeMounts:
        - name: espocrm-www
          mountPath: /var/www/html
      volumes:
      - name: espocrm-www
        persistentVolumeClaim:
          claimName: espocrm-www
      - name: espocrm-customisations
        configMap:
          name: espocrm-customisations
          defaultMode: 420
