apiVersion: v1
kind: Secret
metadata:
    name: espocrm-env
type: Opaque
stringData:
    ESPOCRM_DATABASE_PASSWORD: ENC[AES256_GCM,data:7EjnI7iUvbDPyQI8Drt+L/GLobcg3OIDhbw6U9sDfUI=,iv:4tpo+kgQPPGuA098lSUC44UtnJiROwNcYVgiktxjGBo=,tag:cxpvMNodWbMQEFLQelADTA==,type:str]
    ESPOCRM_ADMIN_PASSWORD: ENC[AES256_GCM,data:75cJ8NNe0mrrAfmh,iv:cfufrSj12wHclQlHLieiwzTi+ox9UA/3nCldjstgQhU=,tag:u5n9OSM7oUNZ6AMwN63yPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOWFZK0F5b2tXeEJ0clB3
            R3pFY3FDb0NJVVlDenVrZ0I2QStHQmVvYzFBCnhzN1VFYWNMekVzZzB3SzRXQkhk
            Q3JZSXV1M0g3UUxsUW1kb3VOU1ZGbEUKLS0tIEJFMXZia3JYUzVWdlZPdFhBZ29P
            ako3VWNGMFlteFZ6aHRCYWlXdk00UFUKHNSOzmluH1LhHUkXSSbdh5Ud3RHEr0h/
            jaVEG5HqcDSWyuuWB4jgJ560ulkH8pub1MUlrQ3Vi3+t0M8jKFvkVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
    lastmodified: "2026-05-26T12:22:01Z"
    mac: ENC[AES256_GCM,data:iMGYgIPTT+N1ew/CXH2Rr1zRqDrXqSsfyoKcupO9d+bpev8sl4vtpKW2fDhljProt+fg8S5I75KK7Nj9Y7Ly68Duv2vobRetscAS/rYyfSOtXqPoOz5RJDGzlvjPaQONM5xcrh1kC2nsBOZ0gmkxGC06ApMEkpGDvz3lceGxQIc=,iv:6i0drwgdJ1laX6eMp2X7im6z2eymt39+qC5jqJZ3vn0=,tag:9YS/Ctad6gKKX4sU1Kqz1g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
