apiVersion: v1
kind: Secret
metadata:
    name: espocrm-postgres
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0qeMc0kUqfxCfMER4uN6TrM38qMNn6MMg27DKektrf0=,iv:pv71kC66U5eEL70rT3nVDa6vdj+d853e9avMsXq5F6w=,tag:9C23aoN4hh1qeB3pWIFO7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYzNuRWdXSS9OdC9PaXk5
            WnEyVE5PcWVqQ01BM0dTN0tyQmU1UjloZEZnCnZEQUJCRm9FaWxMcHFaS0RjSGwy
            QWpHQVJ5Zm5zVmdkNmluTThqVGJKdzAKLS0tIHVJam5ZWkJzS1dyWUU5WjdlWjRk
            UzY4dnlBM3BCaGVheG1Rb3RSaGtWcnMKkdigj3K49E0NcUQRd58O2EiB9Qx3Ld6U
            MbmQIY5HtSn5NW1m0i8NDXZyf8LiuLOUUQ2M076siDElEdZHYZjZaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
    lastmodified: "2026-05-26T10:51:44Z"
    mac: ENC[AES256_GCM,data:xIAPcZyUGfwj9ygbBFvKLzXv+MPyNCT3QddHN00N81bOdwy+zOS0RNKyCQRRvtDF+AzVpKL7v6gj8q8ww1w9kLiwPWCOoKtDEZ2jhXfFxGKJEmJDOkJB261FxXQHX9+LdHZC7MrNn8iAcnPTdan2My9HPOkqDYxuhhWqUTR9qmw=,iv:AMB0DRMhhEXwfRtxNrLKgxY+2A7xz6MOMEN3UKAjqBE=,tag:xM/rZFHsUk50r1cKg3s59g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
