apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prometheus
  labels:
    prometheus: scrape
spec:
  jobLabel: prometheus
  podMetricsEndpoints:
  - port: web
    metricRelabelings:
    - targetLabel: cluster
      replacement: hetzner-01
      action: replace
    honorLabels: true
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
