apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  retention: 7d
  enableOTLPReceiver: true
  scrapeInterval: 1m
  serviceMonitorSelector:
    matchLabels:
      prometheus: scrape
  serviceMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      prometheus: scrape
  podMonitorNamespaceSelector: {}
  additionalScrapeConfigs:
    name: secret-prom-scrape-configs
    key: scrape_configs
  resources:
    requests:
      cpu: 100m
      memory: 400Mi
    limits:
      memory: 400Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 20Gi
