apiVersion: v1
kind: Secret
metadata:
    name: secret-prom-scrape-configs
type: Opaque
stringData:
    scrape_configs: ENC[AES256_GCM,data:Y/q63H2yuWwqH0nf9xoBT6ECsPyErG2UYyqtNLCpIAf/daViGGgTKkKETyNuJqFyp+gbDQYiZTT6WHmz/PXnnecIQXkELn1zdetpu4+UXU0an8mhyzzMcWT6YNoFXpHCF05sHct+SdiMKXggCSGdW33Yp8O/Y/gURt/r7eObfqkdk9eAH1JdBvh5Yk426RVo+y434a5rDVEmEyYu/47bl++fKMnba1e6Cdqgqpw627+7Z+Y+nElXB3kf5/S6FJxDC5ZTsJbRa8SUKWuG/WRHMbKiWhG5aunbyArcFpXQLrEZf4zwGI6oH4ZlC9no6xSrvQ8i3kh9Av+BbkOiGeaBTCbWnDLwPfv/Z3pK16l1kMZWlCtrHyg6zw028qcgibfL0VPalz4AtGVv3giq6mWMgIh1zi4CChw3DEHLJPG2eS6diRGzRDMwM+DKBguzFlc37pb9+h9tnHTBXvCq7rFkCkHJv1pYcZ2jqxzkFWpBUrJlAth4+bvQzzy5+jxpmPH8JuyPoEUXei4SmpXAqG1QINptPiLRYC6qXK4O9BK3HuwFvMIxw/hdtQnl9MluQeboOb6SVPA7ICuLbEMg4Um2ALgY3mvju5cmLoef6UNEwBLiIQPwu09fnNia3EeB2ZIZVZypPtdnGcfxlNNXSw/6BR6wrjWkVQ2COupcKWb8wm9QOoqMyZcUChk4cWpK9lpNiVbbXC8/D1OAdYMBaXDaBcIfVGMwI0ULZIlNbvJaePXoD0aJkXKC7VVUdX2mSwESYoKO9d0BBW6yhyQUzeUBpsHoGoTeaaWOUSJOArYIri+CMk5eTU/rKUqmuWreGhA9UaJAOk9bdFI6hGgaQPTTOdiv8wF4fVxW+OXv5jdin7y0/pN6iya1gw89/l3fNiXsfLgKJAGILLxX78yOBy6gJd61o7wVJgHeeXgAr1RlePA+5EaT4YsVc6P/e9kVgZ5UjxQLaII58+QawGrUdqra0Etl9g==,iv:rsvYZmrHdogB15zQFUMeNkaTL9CENueEmOBRg44J1TY=,tag:Go1SYWsyxdkxhHvx7YEOeg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YkdYblZxQUZhNUhHV1Yx
            eisxbndhejY3Z1J3YVdhZWMwWkhwak9OWmlNCmY0bDdIKy9tVWszVTE2OXE1Z0Fv
            WVZsM3hxdnUxK3VxY0swV3RtcWg2eE0KLS0tIFB5Ym41Z0NwdzgvdGMwaTZXdVRC
            UXByS2MzU2o1a05xWkdBcnBnYUt1dVEK5jMQXFTwj9Xt57iG1NBspUDWJIEHyXSL
            kkcAGKF09n3zf+1cNoyiNqdnBJQhGMz/KJopwT8joaOXhD3nuZuERw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
    lastmodified: "2026-05-25T13:25:51Z"
    mac: ENC[AES256_GCM,data:6YOhYtCxo3L2VF61pNjNG6t0h5FBN07OLfdN7h7bo6JFRdpTfYeLNYRF0t4FqLxiNJSgaOvDLBJTeS0cSSupfM3NUL6n43iCQzA6vbdP6eI4ILxH0Ppc4ckHQEoqQwOg+Kiz39Qb6HJvVXsFvnG/CVj2bmyraA5Mi65lJicbN2s=,iv:bxNjkU9vIhcaiTTwDngvorQ24DgAZVcpIAGU7tz6vAc=,tag:bnf7b5ZMSB7fUsOoGuxaBA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
