apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: keycloak
spec:
  gatewayClassName: traefik
  listeners:
  - name: web
    port: 8000
    protocol: HTTP
    hostname: id.techwerkers.nl
  - name: websecure
    port: 8443
    protocol: HTTPS
    hostname: id.techwerkers.nl
    tls:
      mode: Terminate
      certificateRefs:
      - name: keycloak-tls
        namespace: keycloak
