---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cert-manager
- docmost
- espocrm
- excalidash
- gancio
- infra
- keycloak
- listmonk
- n8n
- oauth2-proxy
- observability
