apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana
spec:
  repo: https://grafana.github.io/helm-charts
  chart: grafana
  version: 10.5.15
  targetNamespace: observability
  createNamespace: true
  valuesContent: |-
    resources:
      requests:
        cpu: 200m
        memory: 384Mi
      limits:
        memory: 384Mi
    initChownData:
      enabled: false
    grafana.ini:
      auth.generic_oauth:
        enabled: true
        name: Keycloak-OAuth
        allow_sign_up: true
        client_id: grafana
        client_secret: ${KEYCLOAK_CLIENT_SECRET}
        scopes: openid profile email offline_access roles
        email_attribute_path: email
        login_attribute_path: username
        name_attribute_path: full_name
        auth_url: https://id.techwerkers.nl/realms/techwerkers/protocol/openid-connect/auth
        token_url: https://id.techwerkers.nl/realms/techwerkers/protocol/openid-connect/token
        api_url: https://id.techwerkers.nl/realms/techwerkers/protocol/openid-connect/userinfo
        role_attribute_path: "contains(resource_access.grafana.roles[*], 'admin') && 'Admin' || contains(resource_access.grafana.roles[*], 'editor') && 'Editor' || 'Viewer'"
        allow_assign_grafana_admin: true
      server:
        enable_gzip: true
        root_url: https://grafana.infra.techwerkers.nl
      unified_alerting:
        enabled: false
      log.console:
        level: info
    persistence:
      enabled: true
      type: pvc
      size: 1Gi
      storageClassName: local-path
      accessModes:
      - ReadWriteOnce
    serviceAccount:
      create: true
      name: grafana
    admin:
      existintgSecret: grafana
      passwordKey: admin-password
      userKey: admin-user
    command:
    - "sh"
    - "-c"
    - "grafana-cli admin reset-admin-password ${GF_SECURITY_ADMIN_PASSWORD} && /run.sh"
    envFromSecret: grafana-env
