apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
- helmchart-grafana.yaml
- httproute-grafana.yaml

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: observability-grafana
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
  files:
  - secret-grafana-env.enc.yaml
