apiVersion: v1
kind: Secret
metadata:
    name: grafana-env
type: Opaque
stringData:
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:RIeP0z3V5QBal4q94LYURfhiWxM38qjs+UA26K4KPOU=,iv:CnDhie2It2bP83O700gFd3So3JrrepFcAQHH/fnjGKg=,tag:jEbQAe+hNg1JTYvqT+28+g==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:JlcAUAWikjv+IE5c5yB7YdJgQvVZe4JIY/34gUKQaSeeN1/uVlJZGg==,iv:gHhiSkv+J8jONxwFFedAEp2JgxVIDAgwGv1W8qnGKiw=,tag:YjNx3/QEZ+vPasNXVl3H7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUUxaV0M2dUFLdVhwZ1lQ
            MmxSQ1RKdnBhMEN1Q2J6K1g2ZTFIbkJpVFV3CkVvRlBCTGRaT284VDBBSFpTUlBQ
            eWpYbVNxTXlFd1BEL3JpaWptYW5SaUEKLS0tIHNpNGRsNzlFeTRoZGtNNk1XcGJD
            MWhxZmxEREJCbzNTTVdPNmtXRGpFUEEKU8sF5/q3+9hg3YUVSimdAZOjnEAOYODv
            8ju5dUOXEVi32dgDSV351SYrPS/Ge8rsuQnzVS8pBVrKb/QYtN4dTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
    lastmodified: "2026-05-25T12:55:22Z"
    mac: ENC[AES256_GCM,data:lM+IbtoKw3AzrqZxXvvJ9kE58jqqwwUNt25CqSYLz7Wf2CX41o9dn3v9gOwL96J+cE8DQb9Nd16/qhUfZX7mUeNsOqf9Dky91MIU3rHMCsBvh8q2coF5KvpugnrUiRSjSUj9nViZVzaAh1sBebKuCkh8AbQUJZOrpL1HSxMrPsk=,iv:evtzXnL2LzPGcVbN9yz33n7SS64sfegFu9X/BIh1oRI=,tag:Y3OJWSvFmJ8kY5oys2j0cw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
