apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-keycloak
    namespace: oauth2-proxy
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:APP7rU3uTttAcTfl,iv:1vInk3spQgQhRl+pJChAnNe+1dL7qNBLlZ078iwZzX4=,tag:5F9q1BMQ53mytM9gybMOEQ==,type:str]
    client-secret: ENC[AES256_GCM,data:flq6IspSA7o1DPdJdQOg2V3nESXF3w4AH8TZOjGPWrw=,iv:daqQ7cyfI7FKKSS747SVCISlICOsIBLlx5IY9IROpaw=,tag:E9W4h5DQ75Ey+AdKat25RQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:EAmmMHtMiVOcd/iuXxpbW+9LYlkzozYluhld7Iy5c6I=,iv:zwMlaMLLsG1h4D7A+GDCKW2MueE723wSk2fzi7f2FBk=,tag:Pgvxm/5OqFJeXhsydsWJNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVV0F5Nk9jUnNlbW5KSWJP
            L0Q1NGI3MGNvWXptYlMxR0cwamxFU3FMc1h3CkFkWTViT1lKNW1YYlhKejBnVFMz
            VFMzanNWd2FZWjF2VW14cStwbjNxVmcKLS0tIEkwVi9WbXl4VUlyQ2hGOU44eERI
            S1NwMDRIZTdTS2lOdG9ubi9mZDd2dTgK/TXtRXY7cHaIwXg3bTBeF7l6JtjI7pFQ
            GrZ6S+HFkri8p+VqumdE/tGixGeEXMVAL1TRz8z1WYikxoTjMiXiCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
    lastmodified: "2026-05-25T12:15:07Z"
    mac: ENC[AES256_GCM,data:RYCedxwPYGQat8DSRCj1YEBPEA1YRhpc1CJX3ACOiXMMDVwgk/OKjJToZg19BqNEZuPAizgTfo3HGt1x2dvWxah5YdzJSry3EcCm32LE04Wh4bo71GU6AE4qvLxBVVs463WGvH3A9L0d/Jnvw+B3Brcf8fKXkF0nhcJh03qy1/A=,iv:BSilUzjXTjw9Oim1dhQA+gNBmU3fGMt82Tce597Qwko=,tag:RQqOr78gRZ3ItU/k33wutg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
