apiVersion: v1
kind: Secret
metadata:
    name: keycloak-env
    namespace: keycloak
type: Opaque
stringData:
    KC_DB_PASSWORD: ENC[AES256_GCM,data:prMELwnaHc/8IiUJ2iX/7eUjQaQ8X9PenAU2CJwqU0uivjCCa8sHguDopiuO07oHGnFDOw5nxS1lyLEaU2aDcw==,iv:wxMew6FeGX5u3igyIb8YOrDoIxlYeX61cNRJ1bR5B/o=,tag:Y/KZqar9qwrsguvvFMzacA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NTRvcjg2VlJCVHBWOFgx
            YXRFSFpGWTAza2FhSUZONE9VWTRSTEM4cTBNClF3RVhPS0hOa3dhR0FNUmN2OVcy
            bUx1b3RPV3BycGpJVlB2eW9kdlE0aUUKLS0tIFFzV3ZPZDNLb2VxVzhDTnBsWWMw
            ZlBLbzRBS0JFQ2tEcGR1RENCZmFxUUkKTOiRjmWgbUiATC/il33r2MKny4zwSlxN
            Es6UMO0Ar86FrebzEt4Wch92jBMyrnEf7N00SB6vlO14Q5qhDhCvPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
    lastmodified: "2026-05-10T18:01:51Z"
    mac: ENC[AES256_GCM,data:ulESoQEhsk/clZk5AYqsEGZQjLuQsEjbg2oIWZfty+h6UMycQJ+0hfJCdNZZbMyZVugsP6kPswyXp1s3fX0Tsdv8QIq4DpsiEFrVwbAuUN/pMMT4hNcXz4uzJrYrAcYOCmoz9MrCWV6Dk2aNCtCcbAoRTpEPg55SdxZkRQcIKzQ=,iv:1UpPDfzwBKYplkyfo7ITvld2a7nr3YFU/vK52cEh79Q=,tag:G4stqW+xq6AcZHSnw+0CFQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.0
