apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgres
    namespace: keycloak
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ME8H4KAp0CRdfTZDgSZpeV7snShXhZxptNiXl04dB7uPX6s4q0NT6YI3qk3jgMCiitGwISIp89AvGQSjrcyRKA==,iv:21KbIR8H9xfYWK0ZHt42FLSeZhq6I+Up+6CtF34mJ34=,tag:IkaVETO2MZlLD/+KH3IUPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEd1lQVFZtVzdicUJ0aFJG
            M2NxdzFkdnc0NVMvQUZNaU1CeWQ4OFdHakZZCjNadFhMMzZJQS96UXd6M0Z5eEhn
            U2pXRzlKdmJKTG0rbEpuUythU0RldlUKLS0tIGpJN3ZXdC9Wb29zbkxKRFNSVkg2
            SmpQNnV5M1pxbXA5cmdWNUZDUGFlWnMKMuiOiEHye2iOUSJugQho273TupUKaROW
            w39Ljf9emV58gXiVhjabbEBTGU3VJzsLMe1RIhYqzXVV/Y9W4Xa+Tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
    lastmodified: "2026-05-10T18:02:01Z"
    mac: ENC[AES256_GCM,data:9gSyb/k/MsHPdqq+eG8lXQcdaTlnwEcJzhoLaYPbCELtb/aTjV/oCmX2ChEh3lRYK7YZ59cuPM402OmwzXChNJczGF/FVJ1Cnqy5x245o0uaaa/r8sbYwf/w81fhyThTiLfoVsmEDApveCLuQL9i2bbxTeF/T42tut1mZePsf2Y=,iv:qOh2GA/Be0bBHW4yV6H7ECksdwm8ImWS/PSB2ejuK70=,tag:4cWBt6fDHomTeLT4WM8hDw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.0
